kind: Deployment
apiVersion: "apps/v1"
metadata: 
 name: "callme-service"
 labels: 
  app: "callme-service"
spec: 
 replicas: 1
 selector: 
  matchLabels: 
   app: "callme-service"
 template: 
  metadata: 
   labels: 
    app: "callme-service"
  spec: 
   containers: 
    - name: "callme-service"
      image: "docker.io/cereus725/callme-service:v1"
      imagePullPolicy: Always
      ports: 
       - containerPort: 8091
      resources: 
       limits: 